# !-----------------------------------------------------------------------------------------------!
#                       Welcome to the main configuration of ${project.name}
# !-----------------------------------------------------------------------------------------------!
Version: 1
Prefix: "&8[&9Claim Fly&8]&e"
Log_Lag_Over_Millis: 100
Debug: [ ]
ClaimFly:
  ChatPrefix: "&8[&9Claim Fly&8]&e"
  ignoreCreativeMode: true
  ignoreSpectatorMode: true
  # EXPERIMENTAL - on large servers this may have an impact on performance
  # Players wont need to use /claimfly command to be able to fly if this is enabled
  # *NB* This will allow flight, not make them start flying.
  AutoAllowFlightOnEnterClaim: false
Messages:
  noFlyPerms: '&cYou do not have permission to fly on this server!'
  # Accepts %ClaimOwner% placeholder to get the current claimowners name
  noFlyThisClaim: '&cYou do not have permission to fly in this claim! Ask &6%ClaimOwner% &c for /accesstrust.'
  noFlyOutsideClaims: '&cYou cannot fly outside of claims!'
  FlightEnabled: 'Flight mode has been enabled.'
  FlightDisabled: 'Flight mode has been disabled.'
